In [5]:
a=5

In [6]:
print(a)

5


Using Numpy

In [7]:
import numpy as np

In [8]:
list=[1,2,3]

In [9]:
np.array(list)    

array([1, 2, 3])

In [10]:
arr=np.array([14,5,6])

In [11]:
print(arr)

[14  5  6]


In [12]:
type(arr)

numpy.ndarray

In [13]:
arr

array([14,  5,  6])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3,6,0.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [27]:
np.random.randint(2,100)

9

In [28]:
np.random.seed(101)
arr=np.random.randint(0,100,10)

In [29]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [30]:
arr.max()

95

In [32]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [33]:
mat=np.arange(0,100).reshape(10,10)

In [34]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Pandas

In [35]:
import pandas as pd

In [36]:
mat[1,2]

12

In [37]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [39]:
arr[:]

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [40]:
arr[1:]

array([11, 81, 70, 63, 87, 75,  9, 77, 40])

In [41]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [44]:
arr[1:3]

array([11, 81])

In [50]:
mat[:2,1:5]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [53]:
mat > 50    

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [54]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])