# TF Syntax Basics

In [2]:
import tensorflow as tf

In [39]:
myrndn=tf.compat.v1.random_normal((4,4),seed=67,stddev=0.05)

In [55]:
myrndn2=tf.random_normal_initializer(0,seed=67,stddev=0.05)

In [59]:
print(myrndn.numpy())

[[-0.01144998  0.02684801  0.01481298  0.00199578]
 [ 0.01090719  0.01136469  0.03803404 -0.06382672]
 [-0.00669858 -0.01343487  0.09131265 -0.03589868]
 [ 0.01184704 -0.01197057 -0.07420035  0.00716014]]


In [36]:
sess.close()
sess=tf.compat.v1.InteractiveSession()

h:\pythoninstalledfiles\lib\site-packages\tensorflow_core\python\client\session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [44]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [45]:
a.get_shape()

TensorShape([2, 2])

In [46]:
b = tf.constant([[10],[100]])

In [47]:
result = tf.matmul(a,b)

In [49]:
result.numpy()

array([[210],
       [430]])

In [43]:
print(sess.run(myops[0]))

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [34]:
myrndn.shape

AttributeError: 'RandomNormal' object has no attribute 'shape'

In [33]:
print(tf.fill((4,4),6).shape)

(4, 4)


In [31]:
sess=tf.compat.v1.Session() #as Session() no longer exixts in tf v2

In [1]:
# import tensorflow as tf
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()

In [3]:
print(tf.__version__)

2.0.0


In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [7]:
print(hello)

tf.Tensor(b'Hello ', shape=(), dtype=string)


In [13]:
with tf.compat.v1.Session() as sess: #we are using with so that we don't have to close the session separately
    result = sess.run(hello+world)

RuntimeError: Attempting to capture an EagerTensor without building a function.

In [21]:
print(result)

b'Hello World'


In [23]:
a=tf.constant(10)
b=tf.constant(20)

In [24]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [26]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [27]:
result

30